import {Inter} from "next/font/google";
import {Provider} from "./provider";
import {Header} from "@/components/Header";
import 'react-toastify/dist/ReactToastify.css';
import {ReactNode} from "react";
import {cookies} from "next/headers";
import {validationToken} from "@/utils/validationToken";
import {redirect} from "next/navigation";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

type Root = {
    children: ReactNode
}

export default async function RootLayout({children}: Root) {

    return (
        <html lang="en">
        <body>
        <Provider>
            {children}
        </Provider>
        </body>
        </html>
    );
}
